### ISSUE TITLE
some strings cannot be translate

### ISSUE THREAD

**Issue by bhavel** [andrewnicols/moodle-local_usertours#10]
I found 2 strings, that arent correct on dashboard page
**Reset user tour on this page
End tour**
tnx Bohus

**Comment by andrewnicols** [comment]
Hi,

In what way aren't they correct? They both look correct to me.

**Comment by bhavel** [comment]
![tour](https://cloud.githubusercontent.com/assets/1582691/17738338/1ec4132c-6491-11e6-8b15-7b6f2d37ca14.png)
marked in red
Bohus

**Comment by andrewnicols** [comment]
I assume that you mean these strings have not been translated.

Translation for this plugin is provided via the standard Moodle Translation procedures.
Please see the documentation at https://lang.moodle.org/ for how to contribute language fixes.

**Comment by bhavel** [comment]
OK, all strings are translated, you can see that string Reset ...isnot follow by name of stringid like other strings on page,
So 2 buttoms are in czech, no so End ...
Bohus

**Comment by andrewnicols** [comment]
These names are added by JS. Perhaps this is why they are not shown.

`End tour` => https://github.com/andrewnicols/moodle-local_usertours/blob/MOODLE_31_STABLE/lang/en/local_usertours.php#L93
endtour,local_usertours
https://github.com/andrewnicols/moodle-`Reset user tour on this page` =>  local_usertours/blob/MOODLE_31_STABLE/lang/en/local_usertours.php#L66
resettouronpage,local_usertours

**Comment by bhavel** [comment]
All is OK
Tnx
