### ISSUE TITLE
Support multi-lang filter

### ISSUE THREAD

**Issue by nadavkav** [andrewnicols/moodle-local_usertours#11]
Feature request: Add support for multi-lang filter, to enable multi lang instructions in each step.

**Comment by andrewnicols** [comment]
Hi Nadav,

This is already supported and there are already several tours out there making use of this feature.

**Comment by nadavkav** [comment]
Interesting...
So I wonder why it is not working for me.
Can you give an example or a link to a multi lang tour usage?

**Comment by nadavkav** [comment]
Ok. I found a link for a demo: https://moodle.net/mod/data/view.php?d=2&rid=269
But it is not working, although I have the filter turned on.
Any ideas?

**Comment by andrewnicols** [comment]
Hi Nadav,

At which point is it not working?
The Admin UI is not translated (to allow editing), whilst the steps should be.

**Comment by nadavkav** [comment]
It is not working when the tour is running on a "add an assignment page"
I have used a tour from the repository (see above) and also made one myself. 
Non work.

**Comment by andrewnicols** [comment]
Hi Nadav,

At the moment the plugin treats all step content as strings rather than text - this means that you must have the multilang filter operate on "Content and headings".

I'll try and address this change in my next release.

**Comment by nadavkav** [comment]
This is what I did.

**Comment by andrewnicols** [comment]
Hi @nadavkav ,

Do you mean that switching to "Content and headings" addressed the issue, or that you tried this already and it did not?

**Comment by andrewnicols** [comment]
This will be included in the next release - I hope to release in the next two weeks.

**Comment by nadavkav** [comment]
I already tried it this way and it did not work.
Tomorrow, I will have time to xdebug it and see why it is not using the filter.
maybe it is something silly :smile:

**Comment by andrewnicols** [comment]
Thanks @nadavkav ,
I've tried to replicate here specifically on the "Add a new Assignment to Topic 1" page, but so far without success.
The tour renders in the same context as the current page, so if the current page does not have the filter enabled, it won't work in the tour.
So easy things to check first:
- is the filter enabled for Content and headings on the course
- are the multilang tags correct

**Comment by nadavkav** [comment]
It work fine (I mean... Great!), Me bad. 
I was not reading the Hebrew translation of the English "Content and headings" correctly, and It was actually initially set to "Content" only. When switching to "Content and headings" everything started to work just fine.

Thank you for your time and for being patient with me.
Nadav :smile:

**Comment by andrewnicols** [comment]
A phew - I'm glad that we could find the answer.

I'll be pushing out a new version of the plugin which switches to support of just "Content". I've already pushed the patches but I haven't released it yet. They're on the MOODLE_31_STABLE and MOODLE_30_STABLE branches if you'd like to try them.

Thanks for letting me know,

Andrew
