### ISSUE TITLE
PARAM_URL instead of PARAM_RAW

### ISSUE THREAD

**Issue by mchurchward** [andrewnicols/moodle-local_usertours#2]
Hi
In classes/external/target.php on line 130, the PARAM_RAW specifier is used for what looks like it should be a PARAM_URL argument. Should it be?

**Comment by mchurchward** [comment]
There are other PARAM_RAW uses that should be reconsidered as well:
- classes/external/tour.php line 91, 94, 149.
- classes/forms/edittour.php line 75
- classes/target/selector.php line 68

**Comment by nadavkav** [comment]
+1

**Comment by andrewnicols** [comment]
I've corrected some of the highlighted items, but not all as not all are bugs.

The URL ones have been corrected - these were previously wrong.
The Step title has been corrected to PARAM_TEXT (from _RAW).

The other cases were correctly _RAW because they may contain HTML and not just multilang.
