### ISSUE TITLE
Hard-wired English language strings

### ISSUE THREAD

**Issue by germanvaleroelizondo** [andrewnicols/moodle-local_usertours#3]
Hi,
I like the user tours plugin a lot.

But the strings used for the buttons: Prev / Next / End tour are not translatable.

**Comment by nadavkav** [comment]
I am also experiencing this, but I think it is an issue with mustache templates not using the translation strings correctly, (Am I right?)

**Comment by andrewnicols** [comment]
Will hav a fix for this shortly in the form of a new release.
The issue was that, although the template was using the language strings, the template was not added to the tour configuration and so it was ignored.
