### ISSUE TITLE
Errors found in XMLDB file: PATH attribute does not match file directory: local/usertours/db

### ISSUE THREAD

**Issue by DR-Bi** [andrewnicols/moodle-local_usertours#39]
Our Moodle server is on Moodle 3.5.3 (Build: 20181112).

Tried to install: 

> 3.1 (Build: 2016052306) (2016052306) Moodle 3.1
> Release date: Tuesday, 30 August 2016, 7:30 AM

 from https://moodle.org/plugins/pluginversions.php?plugin=local_usertours 

Received the following error: 

> Upgrading to new version
> local_usertours
> 
> XML database file errors found
> 
> More information about this error
> Debug info: Errors found in XMLDB file: PATH attribute does not match file directory: local/usertours/db
> Error code: ddlxmlfileerror
> Stack trace:

```
    line 352 of /lib/ddl/database_manager.php: ddl_exception thrown
    line 368 of /lib/ddl/database_manager.php: call to database_manager->load_xmldb_file()
    line 594 of /lib/upgradelib.php: call to database_manager->install_from_xmldb_file()
    line 1857 of /lib/upgradelib.php: call to upgrade_plugins()
    line 694 of /admin/index.php: call to upgrade_noncore()
```

**Comment by andrewnicols** [comment]
This plugin is not compatible with 3.5. It is built into Moodle since 3.3.

**Comment by DR-Bi** [comment]
Ah! Fantastic, thank you
