### ISSUE TITLE
Make text boxes for Titles resizable (as are the boxes for Contents)

### ISSUE THREAD

**Issue by germanvaleroelizondo** [andrewnicols/moodle-local_usertours#4]
The text input boxes for the titles of each step are very small. This is OK for regular user tours, but are insufficient when making multi-language user tours.

The text boxes for Content are adjustable, and can be re-sized to accomodate several sentences in order to provide multi-language support. This is the type of text box that I would like for the text input boxes too.

Not being a programmer, I would guess that it should not be too difficult nor time-consuming to change the text input boxes for all Titles, and make life easier for people who really want to have several languages simoultaneously supported in each user tour. As of today, there are several multi-language user tours uploaded into the Moodle.net user tours database.

![user tour small text input box content adjustable size box](https://cloud.githubusercontent.com/assets/2671923/16714514/09386e50-468b-11e6-83d9-b6b4f86b819c.png)

**Comment by andrewnicols** [comment]
Thanks German,

That's a great suggestion.
I'll bear it in mind for the next release which I've targeted for next month - hopefully sooner if I have a few spare minutes! :)

**Comment by andrewnicols** [comment]
Thanks for the suggestion,

This change will be included in the next release which will be available on moodle.org shortly.

**Comment by germanvaleroelizondo** [comment]
Thanks Andrew.
This change will greatly help multi-language sites and translators. I will be looking forward to your next version release.

**Comment by andrewnicols** [comment]
Hi,

I released it about 8 hours ago. Enjoy! :)

**Comment by germanvaleroelizondo** [comment]
Thanks Andrew.
I already upgraded my local sever.

**Comment by germanvaleroelizondo** [comment]
It is now working as expected. The user can easily expand the 'Title' input box to use all the multi-language data.

**Comment by germanvaleroelizondo** [comment]
You can now close this issue as completed.

**Comment by germanvaleroelizondo** [comment]
Hi Andrew,

I am again asking you to change a (different) title window size in the Moodle Tours plugin. 

Please see the following images and notice how difficult it is to edit the title if you need several languages in one tour:

![view tour_1](https://cloud.githubusercontent.com/assets/2671923/20033687/43e2884a-a36c-11e6-9e22-0c8f75e79de4.png)

![view tour_2](https://cloud.githubusercontent.com/assets/2671923/20033688/490f4164-a36c-11e6-85cc-903ae711cb77.png).

I will be looking forward to your reply.
