### ISSUE TITLE
Column comment raise an error with ORACLE

### ISSUE THREAD

**Issue by s-cenni** [andrewnicols/moodle-local_usertours#5]
Hi!
Thank you very much for this plug-in! I'm very happy that you published it! 

I'm testing it with Moodle 3.0 and ORACLE and I had a problem trying to import a tour.
I get this error 
`Debug info: ORA-01747: invalid user.table.column, table.column, or column specification
INSERT INTO w_usertours_tours (name,comment,pathmatch,enabled,sortorder,configdata) VALUES (:name,:comment,:pathmatch,:enabled,:sortorder,:configdata) RETURNING id INTO :oracle_id
[array (
'name' => 'Editing a quiz',
'comment' => 'Tour to explain editing a quiz',
'pathmatch' => '/mod/quiz/edit.php%',
'enabled' => '1',
'sortorder' => 0,
'configdata' => '{"placement":"bottom","orphan":"0","backdrop":"1","reflex":"1","majorupdatetime":1464025754}',
)]
Error code: dmlwriteexception`
COMMENT should be avoided as column name because is a reserved keyword (https://docs.moodle.org/dev/XMLDB_reserved_words).
Nevertheless I was able to import and to create a tour changing this line in  classes/tour.php (line 355)
`'"comment"'    => $this->comment,`
adding double quotes to comment.
I haven't tested with other DBMS yet but I hope my issue will help you to allow this great plugin to work with more system!

Sara

**Comment by s-cenni** [comment]
The same problem happens when I try to show tour:

`Debug info: ORA-01747: invalid user.table.column, table.column, or column specification 
UPDATE w_usertours_tours SET name = :name,comment = :comment,pathmatch = :pathmatch,enabled = :enabled,sortorder = :sortorder,configdata = :configdata WHERE id=:id
[array (
'name' => 'Tour 82',
'comment' => NULL,
'pathmatch' => '/course/view.php?id=82',
'enabled' => 1,
'sortorder' => '3',
'configdata' => '{"placement":"bottom","orphan":"0","backdrop":"0","reflex":"0"}',
'id' => '21',
)]
Error code: dmlwriteexception`

   Stack trace:

```
line 446 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 271 of /lib/dml/oci_native_moodle_database.php: call to moodle_database->query_end()
line 1361 of /lib/dml/oci_native_moodle_database.php: call to oci_native_moodle_database->query_end()
line 1394 of /lib/dml/oci_native_moodle_database.php: call to oci_native_moodle_database->update_record_raw()
line 477 of /local/usertours/classes/manager.php: call to oci_native_moodle_database->update_record()
line 452 of /local/usertours/classes/manager.php: call to local_usertours\manager->show_hide_tour()
line 145 of /local/usertours/classes/manager.php: call to local_usertours\manager->show_tour()
line 35 of /local/usertours/configure.php: call to local_usertours\manager->execute()  
```

**Comment by andrewnicols** [comment]
Hi all,

I believe that this issue should be addressed in the next release of the plugin which I'll be making available on moodle.org shortly.

If you have already installed the plugin on Oracle, you may need to adjust the field manually, or modify the upgrade script (though I'm not 100% sure on this)
