### ISSUE TITLE
Plugin shows box even if element is not existent and setting set to do not show

### ISSUE THREAD

**Issue by Kathrin84** [andrewnicols/moodle-local_usertours#6]
Hi there,

I'm testing your plugin at the moment and generally I like it a lot. However, I don't get it to work correctly.

I saved the setting to not show the box when the referred element is not there. In my example I referred to the block 'Latest Badges':
![setting](https://cloud.githubusercontent.com/assets/4711883/16867590/ed825126-4a72-11e6-8288-9f05d04e9086.png)

This block is not existent in my course and then this happens:
![result](https://cloud.githubusercontent.com/assets/4711883/16867601/fb2c2fcc-4a72-11e6-971c-d243519855c5.png)

It's showing the box, although I don't want it to be shown. Moreover and more crititcal is the fact, that the user cannot escape it anymore. A reload does not affect it, the displaying stays.

Is there a trick I don't know to get it working correctly or is this a bug?

We're working on Moodle 3.0.4+

Cheers,
Kathrin

**Comment by mkpelletier** [comment]
I am also seeing this behaviour.  I have to delete the step in order to prevent it from showing.  When this happens the tip still shows behind the dim layer, but without any button to advance the tour.  The arrow keys work to advance the tour, but this is not a workable solution.

**Comment by andrewnicols** [comment]
Hi Both,

I've just made a new release of the plugin. Could you please check to see whether this his now addressed for you.

I suspect that it may be as one of the issues I fixed back in the middle of June was addressing this issue. It appears that it did not get released on moodle.org/plugins though for some reason.

I'll look into this to try and ensure that I don't miss a release again.

**Comment by cdsmith-umn** [comment]
@andrewnicols Just wanted to let you know that we (U of MN) were having this problem, as well. I've upgraded us to the latest 3.0 version and tested whether this problem is resolved. I can happily report that we are no longer having this problem and it does appear to be resolved.

**Comment by andrewnicols** [comment]
Thanks all,

I'm going to close this issue then as it looks like it was just down to my missing the release.
