### ISSUE TITLE
Make Moodle tree node classes in settings & navigation blocks unique and descriptive

### ISSUE THREAD

**Issue by nadavkav** [andrewnicols/moodle-local_usertours#7]
While making several tours, I found that it is hard to attach a step to a specific tree node element in the settings and navigation blocks, so I opened https://tracker.moodle.org/browse/MDL-55256 .

Please see if I am on the right track with this, and if so... vote :smile: for it on the tracker.

**Comment by andrewnicols** [comment]
Thanks Nadav,

I've pulled that issue into the user tours epic which I'm currently working on so I'll close the issue here now if that's okay with you.

**Comment by nadavkav** [comment]
Great
